ALTER TABLE  `lh_gallery_images` ADD INDEX  `approved_plain` (  `approved` );
ALTER TABLE  `lh_gallery_images` ADD INDEX  `approved` (  `approved` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_12` , ADD INDEX  `pid_12` (  `pwidth` ,  `pheight` ,  `approved` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_4` , ADD INDEX  `pid_4` (  `approved` , `hits` ,    `pid` );
ALTER TABLE  `lh_gallery_images` ADD INDEX `pid_4res` ( `pwidth`, `pheight`, `approved`, `hits`, `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_5` , ADD INDEX  `pid_5` (  `approved` ,  `pic_rating` ,  `votes` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pwidth_2` ,ADD INDEX  `pwidth_2` (  `pwidth` ,  `pheight` ,  `approved` ,  `pic_rating` ,  `votes` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid` , ADD INDEX  `pid` (  `approved` ,  `mtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pwidth` , ADD INDEX  `pwidth` (  `pwidth` ,  `pheight` ,  `approved` ,  `mtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `comtime` , ADD INDEX  `comtime` (  `approved` ,  `comtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` ADD INDEX `pid_com_res` ( `pwidth`, `pheight`, `approved`, `comtime`, `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_7` , ADD INDEX  `pid_7` (  `aid` ,  `approved` ,  `hits` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_6` ,ADD INDEX  `pid_6` (  `aid` ,  `approved` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_8` , ADD INDEX  `pid_8` (  `aid` ,  `approved` ,  `mtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_9` , ADD INDEX  `pid_9` (  `aid` ,  `approved` ,  `pic_rating` ,  `votes` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_10` , ADD INDEX  `pid_10` (  `aid` ,  `approved` ,  `comtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `aid` , ADD INDEX  `aid` (  `aid` ,  `pwidth` ,  `pheight` ,  `approved` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_2` , ADD INDEX  `pid_2` (  `ctime` ,  `approved` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `pid_11` ,ADD INDEX  `pid_11` (  `aid` ,  `pwidth` ,  `pheight` ,  `approved` ,  `hits` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `aid_2` , ADD INDEX  `aid_2` (  `aid` ,  `pwidth` ,  `pheight` ,  `approved` ,  `mtime` ,  `pid` );
ALTER TABLE  `lh_gallery_images` DROP INDEX  `aid_3` , ADD INDEX  `aid_3` (  `aid` ,  `pwidth` ,  `pheight` ,  `approved` ,  `pic_rating` ,  `votes` ,  `pid` );