ALTER TABLE  `lh_gallery_images` ADD  `rtime` INT NOT NULL ;

ALTER TABLE  `lh_gallery_images` ADD INDEX `rated_gen` (  `approved` , `rtime` , `pid` );
ALTER TABLE  `lh_gallery_images` ADD INDEX `rated_gen_res` ( `pwidth`, `pheight`, `approved`, `rtime`, `pid` );
ALTER TABLE  `lh_gallery_images` ADD INDEX `a_rated_gen_res` ( `aid`, `pwidth`, `pheight`, `approved`,`rtime`, `pid` );
ALTER TABLE  `lh_gallery_images` ADD INDEX `a_rated_gen` ( `aid`, `approved`,`rtime`, `pid` );

DROP VIEW `sphinxseearch`;

CREATE VIEW `sphinxseearch` AS SELECT `lh_gallery_images`.`pid` AS `id`,`lh_gallery_images`.`pid` AS `pid`,`lh_gallery_images`.`hits` AS `hits`,`lh_gallery_images`.`title` AS `title`,`lh_gallery_images`.`mtime` AS `mtime`,`lh_gallery_images`.`keywords` AS `keywords`,`lh_gallery_images`.`caption` AS `caption`,`lh_gallery_images`.`comtime` AS `comtime`,`lh_gallery_images`.`rtime` AS `rtime`,`lh_gallery_images`.`pic_rating` AS `pic_rating`,`lh_gallery_images`.`votes` AS `votes`,replace(replace(`lh_gallery_images`.`filepath`,'/',' '),'-',' ') AS `file_path`,replace(replace(`lh_gallery_images`.`filename`,'-',' '),'_',' ') AS `filename`,`lh_gallery_albums`.`title` AS `album_title`,`lh_gallery_albums`.`keyword` AS `album_keyword`,`lh_gallery_albums`.`description` AS `album_description`,`lh_gallery_categorys`.`name` AS `category_name`,`lh_gallery_categorys`.`description` AS `category_description`,`lh_gallery_images`.`pwidth`,`lh_gallery_images`.`pheight`,concat(`lh_gallery_images`.`pwidth`,'x',`lh_gallery_images`.`pheight`) AS `pdimension` from ((`lh_gallery_images` left join `lh_gallery_albums` on((`lh_gallery_images`.`aid` = `lh_gallery_albums`.`aid`))) left join `lh_gallery_categorys` on((`lh_gallery_categorys`.`cid` = `lh_gallery_albums`.`category`))) where (`lh_gallery_images`.`approved` = 1);