<div class="ln-box">
   <a href="<?=erLhcoreClassDesign::baseurldirect('/')?><?=isset($Result['path_base']) ? ltrim($Result['path_base'],'/') : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/gb.png')?>" title="English"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/fre')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/fr.png')?>" title="Français"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/ger')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/de.png')?>" title="Dutch"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/lit')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/lt.png')?>" title="Lietuviškai"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/esp')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/es.png')?>" title="Spain"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/por')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/pt.png')?>" title="Portugal"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/rus')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/ru.png')?>" title="Russian"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/ita')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/it.png')?>" title="Italian"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/ind')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/in.png')?>" title="India"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/nor')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/no.gif')?>" title="Norwegian"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/den')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/dk.png')?>" title="Denmark"></a>
   <a href="<?=erLhcoreClassDesign::baseurldirect('/jap')?><?=isset($Result['path_base']) ? $Result['path_base'] : ''?>"><img src="<?=erLhcoreClassDesign::design('images/icons/lang/jp.png')?>" title="Japan"></a>
</div>